-- begin DEALER_COUNTRY
create unique index IDX_DEALER_COUNTRY_UNIQ_CODE on DEALER_COUNTRY (CODE) ^
create unique index IDX_DEALER_COUNTRY_UNIQ_NAME on DEALER_COUNTRY (NAME) ^
-- end DEALER_COUNTRY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references DEALER_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
-- begin DEALER_MANUFACTURER
alter table DEALER_MANUFACTURER add constraint FK_DEALER_MANUFACTURER_ON_COUNTRY foreign key (COUNTRY_ID) references DEALER_COUNTRY(ID)^
create unique index IDX_DEALER_MANUFACTURER_UNIQ_CODE on DEALER_MANUFACTURER (CODE) ^
create unique index IDX_DEALER_MANUFACTURER_UNIQ_NAME on DEALER_MANUFACTURER (NAME) ^
create index IDX_DEALER_MANUFACTURER_ON_COUNTRY on DEALER_MANUFACTURER (COUNTRY_ID)^
-- end DEALER_MANUFACTURER
-- begin DEALER_COLOR
create unique index IDX_DEALER_COLOR_UNIQ_CODE on DEALER_COLOR (CODE) ^
create unique index IDX_DEALER_COLOR_UNIQ_NAME on DEALER_COLOR (NAME) ^
-- end DEALER_COLOR
-- begin DEALER_VEHICLE_MODEL
alter table DEALER_VEHICLE_MODEL add constraint FK_DEALER_VEHICLE_MODEL_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references DEALER_MANUFACTURER(ID)^
create index IDX_DEALER_VEHICLE_MODEL_ON_MANUFACTURER on DEALER_VEHICLE_MODEL (MANUFACTURER_ID)^
-- end DEALER_VEHICLE_MODEL
-- begin DEALER_VEHICLE_EQUIPMENT
alter table DEALER_VEHICLE_EQUIPMENT add constraint FK_DEALER_VEHICLE_EQUIPMENT_ON_VEHICLE_MODEL foreign key (VEHICLE_MODEL_ID) references DEALER_VEHICLE_MODEL(ID)^
create index IDX_DEALER_VEHICLE_EQUIPMENT_ON_VEHICLE_MODEL on DEALER_VEHICLE_EQUIPMENT (VEHICLE_MODEL_ID)^
-- end DEALER_VEHICLE_EQUIPMENT
-- begin DEALER_VEHICLE
alter table DEALER_VEHICLE add constraint FK_DEALER_VEHICLE_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references DEALER_MANUFACTURER(ID)^
alter table DEALER_VEHICLE add constraint FK_DEALER_VEHICLE_ON_MODEL foreign key (MODEL_ID) references DEALER_VEHICLE_MODEL(ID)^
alter table DEALER_VEHICLE add constraint FK_DEALER_VEHICLE_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references DEALER_VEHICLE_EQUIPMENT(ID)^
create index IDX_DEALER_VEHICLE_ON_MANUFACTURER on DEALER_VEHICLE (MANUFACTURER_ID)^
create index IDX_DEALER_VEHICLE_ON_MODEL on DEALER_VEHICLE (MODEL_ID)^
create index IDX_DEALER_VEHICLE_ON_EQUIPMENT on DEALER_VEHICLE (EQUIPMENT_ID)^
-- end DEALER_VEHICLE
-- begin DEALER_CLIENT
create unique index IDX_DEALER_CLIENT_UNIQ_CLIENT_ID on DEALER_CLIENT (CLIENT_ID) ^
-- end DEALER_CLIENT
-- begin DEALER_PURCHASE_REQUEST
alter table DEALER_PURCHASE_REQUEST add constraint FK_DEALER_PURCHASE_REQUEST_ON_VEHICLE foreign key (VEHICLE_ID) references DEALER_VEHICLE(ID)^
alter table DEALER_PURCHASE_REQUEST add constraint FK_DEALER_PURCHASE_REQUEST_ON_CLIENT foreign key (CLIENT_ID) references DEALER_CLIENT(ID)^
alter table DEALER_PURCHASE_REQUEST add constraint FK_DEALER_PURCHASE_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_DEALER_PURCHASE_REQUEST_ON_VEHICLE on DEALER_PURCHASE_REQUEST (VEHICLE_ID)^
create index IDX_DEALER_PURCHASE_REQUEST_ON_CLIENT on DEALER_PURCHASE_REQUEST (CLIENT_ID)^
create index IDX_DEALER_PURCHASE_REQUEST_ON_MANAGER on DEALER_PURCHASE_REQUEST (MANAGER_ID)^
-- end DEALER_PURCHASE_REQUEST
-- begin DEALER_PERSON
alter table DEALER_PERSON add constraint FK_DEALER_PERSON_ON_ID foreign key (ID) references DEALER_CLIENT(ID) on delete CASCADE^
-- end DEALER_PERSON
-- begin DEALER_LEGAL
alter table DEALER_LEGAL add constraint FK_DEALER_LEGAL_ON_ID foreign key (ID) references DEALER_CLIENT(ID) on delete CASCADE^
-- end DEALER_LEGAL
